import { build } from "esbuild";
import fs from "node:fs/promises";

await buildViewer({
  entry: "../vendor/t3code-viewer/Viewer.jsx",
  output: "../src/viewer-assets.js",
  scriptName: "viewerScript",
  stylesName: "viewerStyles",
});
await buildViewer({
  entry: "../vendor/artifact-viewer/Viewer.jsx",
  output: "../src/artifact-viewer-assets.js",
  scriptName: "artifactViewerScript",
  stylesName: "artifactViewerStyles",
});

async function buildViewer({ entry, output, scriptName, stylesName }) {
  const result = await build({
    entryPoints: [new URL(entry, import.meta.url).pathname],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2020"],
    minify: true,
    write: false,
    outdir: "viewer-dist",
    jsx: "automatic",
    loader: { ".css": "css" },
  });

  const javascript = result.outputFiles.find((file) => file.path.endsWith(".js"));
  const stylesheet = result.outputFiles.find((file) => file.path.endsWith(".css"));
  if (!javascript || !stylesheet) throw new Error("Viewer build did not emit JavaScript and CSS.");

  const source = `// Generated by scripts/build-viewer.mjs. Do not edit.\nexport const ${scriptName} = ${JSON.stringify(javascript.text)};\nexport const ${stylesName} = ${JSON.stringify(stylesheet.text)};\n`;
  await fs.writeFile(new URL(output, import.meta.url), source);
}
