import { build } from "esbuild";
import fs from "node:fs/promises";

const result = await build({
  entryPoints: [new URL("../vendor/t3code-viewer/Viewer.jsx", import.meta.url).pathname],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  minify: true,
  write: false,
  outdir: "viewer-dist",
  jsx: "automatic",
  loader: { ".css": "css" },
});

const javascript = result.outputFiles.find((file) => file.path.endsWith(".js"));
const stylesheet = result.outputFiles.find((file) => file.path.endsWith(".css"));
if (!javascript || !stylesheet) throw new Error("Viewer build did not emit JavaScript and CSS.");

const output = `// Generated by scripts/build-viewer.mjs. Do not edit.\nexport const viewerScript = ${JSON.stringify(javascript.text)};\nexport const viewerStyles = ${JSON.stringify(stylesheet.text)};\n`;
await fs.writeFile(new URL("../src/viewer-assets.js", import.meta.url), output);
